spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://dpg-csu1c7a3esus73c5o8s0-a.oregon-postgres.render.com/event_schedule
    username: db_events_9wwt_user
    password: sTA1L2gp0ko0EV4L6m87M8bIVpwFs9A7
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    username: jixudchh
    password: a2zBWyDm6q37oegQEuL9IffyySB3zaYY
    host: jackal-01.rmq.cloudamqp.com
    port: 5672
    virtual-host: jixudchh

  application:
    name: NOTIFICATIONS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-service.onrender.com/eureka/
  instance:
    hostname: localhost

springdoc:
  swagger-ui:
    path: /notification-service/swagger-ui.html
  api-docs:
    path: /notification-service/v3/api-docs

server:
  port: ${PORT:8081}
